"""Policy source registry and rule metadata for Compliance & Execution Risk Intelligence v1."""

from __future__ import annotations

from .models import (
    AuthorityType,
    OfficialMonitoringMeta,
    PolicyDocumentMeta,
    PolicyProvisionMeta,
    PolicyRegistryMeta,
    RuleClassification,
)

POLICY_REGISTRY = PolicyRegistryMeta(
    base_document=PolicyDocumentMeta(
        document_id="MPLADS-2023-BASE",
        title="Guidelines on Members of Parliament Local Area Development Scheme (MPLADS)",
        short_title="MPLADS Guidelines 2023",
        version="April 2023 Edition (Effective 1 April 2023)",
        effective_date="2023-04-01",
        authority="Ministry of Statistics and Programme Implementation (MoSPI), Government of India",
        source_document_url="https://mplads.gov.in/MPLADS/guidelines/MPLADSGuidelines2023_English_.pdf",
        portal_url="https://mplads.mospi.gov.in/",
        description="Official administrative framework governing scheme implementation, eligibility, sanction timelines, and accounting procedures.",
    ),
    provisions=[
        PolicyProvisionMeta(
            provision_id="PROV-3.2.4",
            document_id="MPLADS-2023-BASE",
            clause_reference="Para 3.2.4",
            title="Sanction / Rejection Timeline",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Sanction or rejection of recommended works shall be issued within 45 days from receipt of recommendation by the Implementing District Authority (IDA).",
            affected_rule_ids=["COMP-01"],
        ),
        PolicyProvisionMeta(
            provision_id="PROV-3.2.6",
            document_id="MPLADS-2023-BASE",
            clause_reference="Para 3.2.6",
            title="Model Code of Conduct Exclusion",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Periods covered under the Model Code of Conduct (MCC) of the Election Commission of India are excluded when reckoning guideline time limits.",
            affected_rule_ids=["COMP-01"],
        ),
        PolicyProvisionMeta(
            provision_id="PROV-3.2.9",
            document_id="MPLADS-2023-BASE",
            clause_reference="Para 3.2.9",
            title="Minimum Sanction Amount Benchmark",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Normally, each work recommended and sanctioned should not be less than ₹2.5 lakh, unless specific reasons are recorded by the District Authority in the sanction order.",
            affected_rule_ids=["COMP-02"],
        ),
        PolicyProvisionMeta(
            provision_id="PROV-3.2.12",
            document_id="MPLADS-2023-BASE",
            clause_reference="Para 3.2.12",
            title="Completion Timeline",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Sanctioned works should generally be completed within 1 year from the date of sanction order. Exceptional cases requiring longer execution must be recorded in the sanction letter.",
            affected_rule_ids=["COMP-03"],
        ),
        PolicyProvisionMeta(
            provision_id="PROV-CHAP-11",
            document_id="MPLADS-2023-BASE",
            clause_reference="Chapter 11",
            title="Accounting Procedure & Financial Settlement",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Implementing agencies must maintain dedicated scheme accounts, submit verified progress vouchers and Utilization Certificates (UCs), and reconcile unspent balances upon work completion.",
            affected_rule_ids=["COMP-04"],
        ),
        PolicyProvisionMeta(
            provision_id="PROV-6.2.6.2",
            document_id="MPLADS-2023-BASE",
            clause_reference="Para 6.2.6.2",
            title="Assistance to Societies, Trusts, and Associations Ceilings",
            authority_type=AuthorityType.GUIDELINE_PROVISION,
            mandate_summary="Up to 10% of total authorization in a financial year for all Societies/Trusts, Cooperative Societies and Bar Associations as applicable, with a maximum of ₹1 crore for any particular entity during the MP's entire term. (Note: 10% equals ₹50 lakh when annual entitlement is ₹5 crore).",
            affected_rule_ids=["DEF-01"],
        ),
    ],
    official_monitoring_benchmarks=[
        OfficialMonitoringMeta(
            monitoring_id="MOSPI-MON-90D",
            benchmark_name="Three Months Post-Sanction Zero-Payment Review Benchmark",
            authority="Ministry of Statistics and Programme Implementation (MoSPI)",
            authority_type=AuthorityType.OFFICIAL_MONITORING,
            source_url="https://mplads.mospi.gov.in/",
            description="Documented MoSPI monthly review benchmark monitoring sanctioned works where no payments have been made three months (90 days) post-sanction. Sentinel v1 implements a 91–180 day operational window to identify early-stage pipeline stagnation for administrative intervention before works enter prolonged dormancy.",
            affected_rule_ids=["MON-01"],
        ),
    ],
    deferred_rules_notes={
        "DEF-01": "Trust/Society Annual & Term Ceilings (Para 6.2.6.2): Work-level Trust/Society ceiling evaluation is not computable from the available fields because applicable limits require entity-level, MP-level, financial-year and term-level aggregation.",
        "DEF-02": "Workflow Milestone Synchronization Lag: 93.4% of works in 'Vendor Identification' have disbursements due to systemic portal reporting lag between treasury feeds and milestone fields. Deferred to v2 Data Quality module.",
        "DEF-03": "Citizen Information Board / Plaque Verification (Para 3.2.17): Mandatory site plaque erection. Column Image in raw portal data contains exclusively 'N/A'; zero site photographs exist in dataset.",
        "DEF-04": "True Cost Overrun / Escalation (Para 3.2.13): Portal system architecture strictly caps disbursements at 100% of sanction. Original estimates, revised estimates, and variation orders are not captured.",
        "DEF-05": "Technical Sanction & DPR Compliance (Para 3.2.13): Engineering estimates and Detailed Project Reports (DPRs) are maintained offline by state line departments and absent from export.",
        "DEF-06": "e-Tender & Transparent Bidding Logs (Para 3.2.13): Competitive bidding notices, tender logs, and bidder counts reside in separate state/central e-Procurement portals, not in MPLADS.",
        "DEF-07": "Trust Eligibility Verification (Para 6.2): Requirements such as 3 years of audited accounts, registered society bylaws, and non-profit certification require external registry documents.",
    },
)

RULE_DEFINITIONS: dict[str, dict[str, str]] = {
    "COMP-01": {
        "rule_id": "COMP-01",
        "rule_name": "Recommendation Latency (>45 Days)",
        "authority_type": AuthorityType.OPERATIONAL_PROXY.value,
        "classification": RuleClassification.POLICY_PROXY.value,
        "source_reference": "MPLADS Guidelines 2023, Para 3.2.4 (read with Para 3.2.6)",
        "threshold": "> 45 days from recommendation submission",
        "description": "Examines whether the duration between recommendation date and sanction date exceeds the 45-day guideline target.",
        "limitation": "recommended_date records digital portal submission, which may differ from administrative receipt by the Implementing District Authority (IDA). Periods covered by election Model Code of Conduct (Para 3.2.6) are unrecorded in dataset.",
        "recommended_action": "Verify actual receipt date at district authority, review administrative processing notes, and cross-check local election MCC dates.",
    },
    "COMP-02": {
        "rule_id": "COMP-02",
        "rule_name": "Below Normal Sanction Benchmark (<₹2.5L)",
        "authority_type": AuthorityType.GUIDELINE_PROVISION.value,
        "classification": RuleClassification.POLICY_TRIGGER.value,
        "source_reference": "MPLADS Guidelines 2023, Para 3.2.9",
        "threshold": "< ₹2,50,000 normal benchmark",
        "description": "Identifies works sanctioned below the normal ₹2.5 Lakh benchmark where recorded justifications may be required.",
        "limitation": "Para 3.2.9 allows the District Authority to sanction smaller works after recording specific reasons in the sanction order. Sanction order narrative justifications are not captured in the tabular dataset.",
        "recommended_action": "Confirm that recorded reasons and necessity justification are documented in the formal sanction order file.",
    },
    "COMP-03": {
        "rule_id": "COMP-03",
        "rule_name": "Extended Execution Duration (>365 Days)",
        "authority_type": AuthorityType.GUIDELINE_PROVISION.value,
        "classification": RuleClassification.POLICY_TRIGGER.value,
        "source_reference": "MPLADS Guidelines 2023, Para 3.2.12",
        "threshold": "> 365 days from sanction order",
        "description": "Identifies works whose completion duration or ongoing duration exceeds the 1-year timeline benchmark.",
        "limitation": "Formal time extensions granted due to seasonal monsoons, litigation stays, or land clearance are maintained in district physical files and unrecorded on the portal.",
        "recommended_action": "Review approved time extensions, revised milestone schedules, and contractor progress reports in district records.",
    },
    "COMP-04": {
        "rule_id": "COMP-04",
        "rule_name": "Completed Work with Zero Recorded Outlay",
        "authority_type": AuthorityType.GUIDELINE_PROVISION.value,
        "classification": RuleClassification.POLICY_RECONCILIATION.value,
        "source_reference": "MPLADS Guidelines 2023, Chapter 11 (Accounting Procedure)",
        "threshold": "Completed status with zero recorded disbursement",
        "description": "Identifies works marked completed in portal registers but having zero recorded disbursements in the financial ledger.",
        "limitation": "Potential reconciliation inconsistency between physical completion reporting and treasury ledger entries; does not represent a determination of non-compliance. May reflect portal sync latency, convergence funding, or administrative closure.",
        "recommended_action": "Verify final contractor billing vouchers, check for convergence scheme funding records, and reconcile unspent balance returns.",
    },
    "MON-01": {
        "rule_id": "MON-01",
        "rule_name": "Monitoring-Derived Early Warning (91–180 Days, ₹0 Outlay)",
        "authority_type": AuthorityType.OFFICIAL_MONITORING.value,
        "classification": RuleClassification.OFFICIAL_MONITORING.value,
        "source_reference": "MoSPI Documented Monthly Review Benchmark",
        "threshold": "91–180 days post-sanction with no payment",
        "description": "Early-warning review window derived from MoSPI's 90-day review benchmark for works with no recorded payment.",
        "limitation": "Derived from MoSPI's 90-day review benchmark. The 91–180 day range is Sentinel's operational window for early administrative warning and does not represent an official scheme deadline or finding of non-compliance.",
        "recommended_action": "Check status of tendering, administrative work orders, and initial mobilization advances with the implementing agency.",
    },
    "RISK-01": {
        "rule_id": "RISK-01",
        "rule_name": "Prolonged Dormancy (>180 Days, ₹0 Outlay)",
        "authority_type": AuthorityType.HEURISTIC.value,
        "classification": RuleClassification.EXECUTION_HEURISTIC.value,
        "source_reference": "Project Pipeline Health Indicator",
        "threshold": "> 180 days post-sanction with no payment",
        "description": "Identifies ongoing works where sanctioned capital has remained completely dormant for over 6 months with zero outlay.",
        "limitation": "Operational pipeline indicator identifying stranded or delayed capital; does not represent an administrative irregularity or finding of non-compliance. May reflect administrative litigation, tendering cancellations, or contractor defaults.",
        "recommended_action": "Initiate district pipeline review to identify bottlenecks, re-tender work, or cancel sanction and de-allocate committed funds.",
    },
    "RISK-02": {
        "rule_id": "RISK-02",
        "rule_name": "Stalled Disbursement (>180 Days Inactive)",
        "authority_type": AuthorityType.HEURISTIC.value,
        "classification": RuleClassification.EXECUTION_HEURISTIC.value,
        "source_reference": "Cash-Flow Velocity Indicator",
        "threshold": "> 180 days inactive on work with < 80% utilization",
        "description": "Identifies incomplete works with partial utilization (<80%) where financial disbursements have halted for over 6 months.",
        "limitation": "Operational cash-flow indicator; seasonal pauses (winter snow/monsoon) or contractor disputes commonly cause interim disbursement pauses.",
        "recommended_action": "Inspect on-ground construction status, verify physical measurement books (MB), and follow up on pending contractor running bills.",
    },
    "RISK-03": {
        "rule_id": "RISK-03",
        "rule_name": "Post-Completion Disbursement (>30 Days)",
        "authority_type": AuthorityType.HEURISTIC.value,
        "classification": RuleClassification.EXECUTION_HEURISTIC.value,
        "source_reference": "Ledger Sequence Review Indicator",
        "threshold": "Payment date > completion date + 30 days",
        "description": "Identifies transactions disbursed more than 30 days after physical work completion.",
        "limitation": "Operational sequence indicator; release of Defect Liability Period (DLP) retention money (typically 6–12 months after completion) or delayed voucher upload is routine engineering practice, not an irregular payment.",
        "recommended_action": "Cross-reference payment purpose against contract terms to confirm whether payment represents DLP retention release or delayed contractor billing.",
    },
}


def get_rule_meta(rule_id: str) -> dict[str, str]:
    """Get metadata for a specific rule ID."""
    return RULE_DEFINITIONS.get(rule_id, {})
